apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/management-components-version: v0.0.0-dev+build.8233
  name: main-i-00bf7-2c27bc6
  namespace: default
spec:
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: main-i-00bf7-2c27bc6
  eksaVersion: v0.0.0-dev+build.8233
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.28"
  machineHealthCheck:
    nodeStartupTimeout: 10m0s
    unhealthyMachineTimeout: 5m0s
  managementCluster:
    name: main-i-00bf7-2c27bc6
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: main-i-00bf7-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: quick-e2e-test-ec15bf50-e1a0-438d-8bdd-9cd3e4d3dd66-3
  clusterConfigPath: quick-e2e-test-ec15bf50-e1a0-438d-8bdd-9cd3e4d3dd66-3
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/quick-e2e-test-ec15bf50-e1a0-438d-8bdd-9cd3e4d3dd66-3.git
  systemNamespace: default

---
